namespace BionicCode.Utilities.Net
{
  using System;

  [Flags]
  internal enum SymbolKinds
  {
    Undefined = 0,
    Final = 1,
    Virtual = 2,
    Abstract = 4,
    Static = 8,
    Class = 16 | Type,
    SealedClass = Final | Class,
    AbstractClass = Abstract | Class,
    StaticClass = Static | Class,
    GenericClass = Generic | Class,
    GenericSealedClass = Generic | Final | Class,
    GenericAbstractClass = Generic | Abstract | Class,
    GenericStaticClass = Generic | Static | Class,
    Interface = 32 | Type,
    GenericInterface = Generic | Interface,
    Delegate = 64 | Type,
    GenericDelegate = Generic | Delegate,
    Struct = 128 | Type,
    ReadOnlyStruct = Final | Struct,
    GenericStruct = Generic | Struct,
    GenericReadOnlyStruct = Generic | Final | Struct,
    Enum = 256 | Type,
    Method = 512 | Member,
    VirtualMethod = Virtual | Method,
    AbstractMethod = Abstract | Method,
    StaticMethod = Static | Method,
    SealedOverrideMethod = Final | Override | Method,
    OverrideMethod = Override | Method,
    GenericVirtualMethod = Generic | Virtual | Method,
    GenericMethod = Generic | Method,
    GenericAbstractMethod = Generic | Abstract | Method,
    GenericStaticMethod = Generic | Static | Method,
    GenericSealedOverrideMethod = Generic | Final | Override | Method,
    GenericOverrideMethod = Generic |Override | Method,
    Property = 1024 | Member,
    ReadOnlyProperty = Final | Property,
    AbstractProperty = Abstract | Property,
    AbstractReadOnlyProperty = Abstract | Final | Property,
    StaticProperty = Static | Property,
    StaticReadOnlyProperty = Static | Final | Property,
    VirtualProperty = Virtual | Property,
    VirtualReadOnlyProperty = Virtual| Final | Property,
    OverrideProperty = Override | Property,
    OverrideReaOnlyProperty = Override | Final | Property,
    Field = 2048 | Member,
    ReadOnlyField = Final | Field,
    StaticField = Static | Property,
    StaticReadOnlyField = Static | Final | Field,
    Event = 4096 | Member,
    VirtualEvent = Virtual | Event,
    AbstractEvent = Abstract | Event,
    OverrideEvent = Override | Event,
    Constructor = 8192 | Member,
    StaticConstructor = Static | Constructor,
    IndexerProperty = 16384 | Property,
    ReadOnlyIndexerProperty = Final | IndexerProperty,
    OverrideReadOnlyIndexerProperty = Override | Final | IndexerProperty,
    OverrideIndexerProperty = Override| IndexerProperty,
    StaticIndexerProperty = Static | IndexerProperty,
    StaticReadOnlyIndexerProperty = Static | Final | IndexerProperty,
    AbstractIndexerProperty = Abstract | IndexerProperty,
    AbstractReadOnlyIndexerProperty = Abstract | Final | IndexerProperty,
    Override = 32768,
    Generic = 65536,
    Member = 131072,
    Type = 262144,
    GenericType = Generic | Type,
  }
}