<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;net9.0;net9.0</TargetFrameworks>

    <IsPackable>false</IsPackable>

    <AnalysisLevel>none</AnalysisLevel>

    <EnableNETAnalyzers>False</EnableNETAnalyzers>
  </PropertyGroup>

  <!--<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|notcoreapp3.1|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|notcoreapp3.1|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>-->

  <ItemGroup>
    <Compile Remove="UnitTests\Profiling\ContextExecutables\**" />
    <EmbeddedResource Remove="UnitTests\Profiling\ContextExecutables\**" />
    <None Remove="UnitTests\Profiling\ContextExecutables\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.12.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.console" Version="2.9.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BionicCode.Utilities.Net.Common\BionicCode.Utilities.Net.Common.csproj" />
    <ProjectReference Include="..\BionicCode.Utilities.Net\BionicCode.Utilities.Net.csproj" />
  </ItemGroup>
  
  <Target Name="MakeMyDir" AfterTargets="Build">
    <MakeDir Directories="$(OutDir)logs" />
  </Target>

</Project>
